# fix: error[E0670]: `async fn` is not permitted in the 2015 edition
# refer: https://git.sjtu.edu.cn/sjtug/doom-emacs/-/blob/2731685095d1e6101b3215aa689426e1834ce00f/modules/lang/rust/README.org
edition = "2021"
